### PR TITLE
Fix CPU temperature (in ºC)

### PR DESCRIPTION
**Pull request by Charlyo**

### CODE REVIEW

**Comment by Charlyo** [comment]
tested on a Thinkpad T460 with an Intel i5 6200U. temperature is accurate using my commit.

With your approach:

Screen Shot 2019-12-12 at 22 14 13

With my PR:

**Comment by Charlyo** [comment]
https://software.intel.com/en-us/forums/intel-many-integrated-core/topic/742762
 
bits 23-16 from 1a2 - bits 22:16 from 19c

**Comment by sicreative** [comment]
I check that the original MacBook device is 0 offset, so this change should not affect the real Apple devices reading, so we could default close the offset and preserve read this value if somebody board require that. Thanks.

**Comment by Charlyo** [comment]
This offset might (?) change between platforms (skylake, haswell, etc). If anyone reports a wrong temperature on another platform, the code should reflect the correct one.

**Pull request merged**
